//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class stdExamQuestion
    {
        public int ID { get; set; }
        public int stdID { get; set; }
        public int quesID { get; set; }
        public int examID { get; set; }
        public string stdAnswer { get; set; }
        public Nullable<int> stdGrade { get; set; }
        public Nullable<int> examNumber { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
