//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int topicID { get; set; }
        public string topicName { get; set; }
        public int crsID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
